import { db } from './client.js';
import { users, listings, reviews } from './schema.js';

async function seed() {
  console.log('🌱 Seeding database...');

  // Check if already seeded
  const existing = await db.select().from(users).limit(1);
  if (existing.length > 0) {
    console.log('✅ Already seeded, skipping.');
    return;
  }

  // ── Seed users ────────────────────────────────────────────────────────────
  await db.insert(users).values([
    { name: 'Arjun Mehta',    email: 'arjun@college.edu',  avatar: 'AM', avatarBg: 'bg-indigo-100 text-indigo-700', location: 'Hostel Block A',  verified: true,  rating: '4.8', totalSales: 8  },
    { name: 'Priya Sharma',   email: 'priya@college.edu',  avatar: 'PS', avatarBg: 'bg-pink-100 text-pink-700',    location: 'Girls Hostel C',  verified: true,  rating: '4.9', totalSales: 14 },
    { name: 'Rohan Kumar',    email: 'rohan@college.edu',  avatar: 'RK', avatarBg: 'bg-orange-100 text-orange-700',location: 'Hostel Block D',  verified: false, rating: '4.5', totalSales: 3  },
    { name: 'Dev Patel',      email: 'dev@college.edu',    avatar: 'DP', avatarBg: 'bg-purple-100 text-purple-700',location: 'Off Campus',      verified: true,  rating: '4.7', totalSales: 6  },
    { name: 'Sneha Iyer',     email: 'sneha@college.edu',  avatar: 'SI', avatarBg: 'bg-teal-100 text-teal-700',   location: 'Hostel Block B',  verified: false, rating: '4.6', totalSales: 2  },
    { name: 'Karan Singh',    email: 'karan@college.edu',  avatar: 'KS', avatarBg: 'bg-blue-100 text-blue-700',   location: 'Hostel Block E',  verified: true,  rating: '4.7', totalSales: 11 },
    { name: 'Ananya Reddy',   email: 'ananya@college.edu', avatar: 'AR', avatarBg: 'bg-rose-100 text-rose-700',   location: 'Girls Hostel A',  verified: true,  rating: '5.0', totalSales: 19 },
    { name: 'Vikram Nair',    email: 'vikram@college.edu', avatar: 'VN', avatarBg: 'bg-green-100 text-green-700', location: 'Hostel Block C',  verified: false, rating: '4.3', totalSales: 1  },
    { name: 'Meera Joshi',    email: 'meera@college.edu',  avatar: 'MJ', avatarBg: 'bg-yellow-100 text-yellow-700',location: 'Girls Hostel B', verified: true,  rating: '4.8', totalSales: 7  },
    { name: 'Aditya Verma',   email: 'aditya@college.edu', avatar: 'AV', avatarBg: 'bg-cyan-100 text-cyan-700',   location: 'Off Campus',      verified: false, rating: '4.4', totalSales: 4  },
  ]);

  // ── Seed 100 listings ─────────────────────────────────────────────────────
  await db.insert(listings).values([
    // ── BOOKS (20) ──────────────────────────────────────────────────────────
    { sellerId: 1, title: 'Engineering Mathematics Vol 1 & 2 Bundle', description: 'Both volumes of Engineering Mathematics by B.S. Grewal. Used for 2 semesters, all pages intact, minimal highlighting. Perfect for first-year students.', price: 450, originalPrice: 1200, category: 'Books', condition: 'Good', location: 'Hostel Block A', image: '/airo-assets/images/listings/textbooks', tag: 'Hot Deal', tagColor: 'bg-red-500' },
    { sellerId: 3, title: 'NCERT Physics Class 12 — Set of 2 Parts', description: 'Both parts of NCERT Physics Class 12. Clean copy, no missing pages. Useful for JEE revision and college entrance prep.', price: 120, originalPrice: 320, category: 'Books', condition: 'Good', location: 'Hostel Block D', image: '/airo-assets/images/listings/textbooks', tag: null, tagColor: null },
    { sellerId: 5, title: 'Introduction to Algorithms — CLRS 3rd Edition', description: 'The classic algorithms textbook by Cormen, Leiserson, Rivest, Stein. Hardcover, excellent condition. A must-have for CS students.', price: 1100, originalPrice: 2800, category: 'Books', condition: 'Like New', location: 'Hostel Block B', image: '/airo-assets/images/listings/textbooks', tag: 'Popular', tagColor: 'bg-violet-500' },
    { sellerId: 2, title: 'Operating Systems — Galvin 9th Edition', description: 'Galvin OS textbook, 9th edition. Some pencil marks in first 3 chapters, rest is clean. Great for OS course.', price: 380, originalPrice: 850, category: 'Books', condition: 'Good', location: 'Girls Hostel C', image: '/airo-assets/images/listings/textbooks', tag: null, tagColor: null },
    { sellerId: 4, title: 'Computer Networks — Tanenbaum 5th Edition', description: 'Tanenbaum Computer Networks 5th edition. Lightly used, all pages intact. Perfect for networking course.', price: 420, originalPrice: 950, category: 'Books', condition: 'Good', location: 'Off Campus', image: '/airo-assets/images/listings/textbooks', tag: null, tagColor: null },
    { sellerId: 6, title: 'Organic Chemistry — Morrison & Boyd', description: 'Morrison Boyd Organic Chemistry. Comprehensive coverage. Some highlighting in first 5 chapters. Great for chemistry students.', price: 550, originalPrice: 1400, category: 'Books', condition: 'Good', location: 'Hostel Block E', image: '/airo-assets/images/listings/textbooks', tag: null, tagColor: null },
    { sellerId: 7, title: 'Discrete Mathematics — Kenneth Rosen', description: 'Rosen Discrete Mathematics 7th edition. Clean copy, no marks. Covers logic, sets, graphs, and combinatorics.', price: 480, originalPrice: 1100, category: 'Books', condition: 'Like New', location: 'Girls Hostel A', image: '/airo-assets/images/listings/textbooks', tag: 'Verified', tagColor: 'bg-primary' },
    { sellerId: 8, title: 'Database System Concepts — Silberschatz', description: 'Silberschatz Database Systems 6th edition. Minor wear on cover, content perfect. Ideal for DBMS course.', price: 400, originalPrice: 900, category: 'Books', condition: 'Good', location: 'Hostel Block C', image: '/airo-assets/images/listings/textbooks', tag: null, tagColor: null },
    { sellerId: 9, title: 'Signals & Systems — Oppenheim', description: 'Oppenheim Signals and Systems 2nd edition. Used for one semester. Clean with minimal notes in margins.', price: 520, originalPrice: 1200, category: 'Books', condition: 'Good', location: 'Girls Hostel B', image: '/airo-assets/images/listings/textbooks', tag: null, tagColor: null },
    { sellerId: 10, title: 'Fluid Mechanics — Frank White 7th Edition', description: 'Frank White Fluid Mechanics. Good condition, all chapters intact. Useful for mechanical and civil engineering students.', price: 600, originalPrice: 1500, category: 'Books', condition: 'Good', location: 'Off Campus', image: '/airo-assets/images/listings/textbooks', tag: null, tagColor: null },
    { sellerId: 1, title: 'Strength of Materials — R.K. Bansal', description: 'R.K. Bansal Strength of Materials. Comprehensive with solved examples. Some highlighting but all readable.', price: 350, originalPrice: 800, category: 'Books', condition: 'Fair', location: 'Hostel Block A', image: '/airo-assets/images/listings/textbooks', tag: null, tagColor: null },
    { sellerId: 2, title: 'Microprocessors & Microcontrollers — Gaonkar', description: 'Gaonkar 8085 Microprocessor textbook. Clean copy. Perfect for electronics and computer engineering students.', price: 280, originalPrice: 650, category: 'Books', condition: 'Good', location: 'Girls Hostel C', image: '/airo-assets/images/listings/textbooks', tag: null, tagColor: null },
    { sellerId: 3, title: 'Engineering Drawing — N.D. Bhatt', description: 'N.D. Bhatt Engineering Drawing. First-year essential. Used for one semester, all drawing sheets intact.', price: 200, originalPrice: 480, category: 'Books', condition: 'Good', location: 'Hostel Block D', image: '/airo-assets/images/listings/textbooks', tag: 'Hot Deal', tagColor: 'bg-red-500' },
    { sellerId: 4, title: 'Artificial Intelligence — Russell & Norvig', description: 'AIMA 3rd edition by Russell and Norvig. The definitive AI textbook. Lightly used, excellent condition.', price: 900, originalPrice: 2200, category: 'Books', condition: 'Like New', location: 'Off Campus', image: '/airo-assets/images/listings/textbooks', tag: 'Popular', tagColor: 'bg-violet-500' },
    { sellerId: 5, title: 'Digital Electronics — Morris Mano', description: 'Morris Mano Digital Design. Clean copy with some pencil notes. Great for digital circuits course.', price: 320, originalPrice: 720, category: 'Books', condition: 'Good', location: 'Hostel Block B', image: '/airo-assets/images/listings/textbooks', tag: null, tagColor: null },
    { sellerId: 6, title: 'Thermodynamics — Cengel & Boles', description: 'Cengel Thermodynamics 8th edition. Excellent condition, barely used. Covers all thermodynamics fundamentals.', price: 750, originalPrice: 1800, category: 'Books', condition: 'Like New', location: 'Hostel Block E', image: '/airo-assets/images/listings/textbooks', tag: null, tagColor: null },
    { sellerId: 7, title: 'Linear Algebra — Gilbert Strang', description: 'Gilbert Strang Introduction to Linear Algebra 5th edition. Clean copy. Perfect for math and engineering students.', price: 680, originalPrice: 1600, category: 'Books', condition: 'Like New', location: 'Girls Hostel A', image: '/airo-assets/images/listings/textbooks', tag: 'Verified', tagColor: 'bg-primary' },
    { sellerId: 8, title: 'Compiler Design — Aho, Lam, Sethi (Dragon Book)', description: 'The Dragon Book — Compilers by Aho, Lam, Sethi, Ullman. 2nd edition. Used for one semester, good condition.', price: 580, originalPrice: 1350, category: 'Books', condition: 'Good', location: 'Hostel Block C', image: '/airo-assets/images/listings/textbooks', tag: null, tagColor: null },
    { sellerId: 9, title: 'Probability & Statistics — Walpole', description: 'Walpole Probability and Statistics for Engineers 9th edition. Clean copy, no marks. Great for stats course.', price: 420, originalPrice: 980, category: 'Books', condition: 'Good', location: 'Girls Hostel B', image: '/airo-assets/images/listings/textbooks', tag: null, tagColor: null },
    { sellerId: 10, title: 'Control Systems — Nagrath & Gopal', description: 'Nagrath Gopal Control Systems Engineering. Used for one semester. Some notes in margins, all content readable.', price: 380, originalPrice: 850, category: 'Books', condition: 'Fair', location: 'Off Campus', image: '/airo-assets/images/listings/textbooks', tag: null, tagColor: null },

    // ── ELECTRONICS (20) ────────────────────────────────────────────────────
    { sellerId: 2, title: 'MacBook Air M1 2021 — 8GB/256GB', description: 'Barely used MacBook Air M1. Battery health at 94%. Comes with original charger and box. No scratches, screen in perfect condition. Selling because upgrading to M3.', price: 52000, originalPrice: 92000, category: 'Electronics', condition: 'Like New', location: 'Girls Hostel C', image: '/airo-assets/images/listings/laptop', tag: 'Verified', tagColor: 'bg-primary' },
    { sellerId: 5, title: 'Sony WH-1000XM4 Noise Cancelling Headphones', description: 'Sony XM4 in excellent condition. Used for 6 months. ANC works perfectly, battery lasts 30+ hours. Comes with original case and cables.', price: 12500, originalPrice: 22000, category: 'Electronics', condition: 'Like New', location: 'Hostel Block B', image: '/airo-assets/images/listings/headphones', tag: 'Popular', tagColor: 'bg-violet-500' },
    { sellerId: 6, title: 'Dell Inspiron 15 — i5 11th Gen, 8GB RAM', description: 'Dell Inspiron 15 laptop. Intel i5 11th gen, 8GB RAM, 512GB SSD. Runs smoothly, battery backup 4-5 hours. Minor scratches on lid.', price: 28000, originalPrice: 55000, category: 'Electronics', condition: 'Good', location: 'Hostel Block E', image: '/airo-assets/images/listings/laptop', tag: null, tagColor: null },
    { sellerId: 7, title: 'iPad Air 4th Gen — 64GB WiFi', description: 'iPad Air 4th generation, 64GB WiFi. Used for note-taking. Screen perfect, no scratches. Comes with Apple Pencil 2nd gen.', price: 35000, originalPrice: 62000, category: 'Electronics', condition: 'Like New', location: 'Girls Hostel A', image: '/airo-assets/images/listings/laptop', tag: 'Set Deal', tagColor: 'bg-amber-500' },
    { sellerId: 8, title: 'Boat Rockerz 450 Bluetooth Headphones', description: 'Boat Rockerz 450 wireless headphones. 15 hours battery, good bass. Used for 8 months. Minor wear on ear cushions.', price: 800, originalPrice: 2000, category: 'Electronics', condition: 'Good', location: 'Hostel Block C', image: '/airo-assets/images/listings/headphones', tag: null, tagColor: null },
    { sellerId: 9, title: 'Realme 9 Pro+ 5G — 8GB/128GB', description: 'Realme 9 Pro+ 5G smartphone. 8GB RAM, 128GB storage. Excellent camera, 50MP Sony sensor. Comes with original box and charger.', price: 14000, originalPrice: 24000, category: 'Electronics', condition: 'Good', location: 'Girls Hostel B', image: '/airo-assets/images/listings/laptop', tag: null, tagColor: null },
    { sellerId: 10, title: 'Casio FX-991EX Scientific Calculator', description: 'Casio ClassWiz FX-991EX. 552 functions, spreadsheet mode. Used for 2 years, works perfectly. Essential for engineering exams.', price: 900, originalPrice: 1800, category: 'Electronics', condition: 'Good', location: 'Off Campus', image: '/airo-assets/images/listings/laptop', tag: 'Hot Deal', tagColor: 'bg-red-500' },
    { sellerId: 1, title: 'JBL Flip 5 Bluetooth Speaker', description: 'JBL Flip 5 portable speaker. Waterproof, 12 hours battery. Excellent sound quality. Used for 1 year, works perfectly.', price: 4500, originalPrice: 9500, category: 'Electronics', condition: 'Good', location: 'Hostel Block A', image: '/airo-assets/images/listings/headphones', tag: null, tagColor: null },
    { sellerId: 3, title: 'Logitech MX Master 3 Wireless Mouse', description: 'Logitech MX Master 3. Ergonomic, 70-day battery, works on any surface. Perfect for coding and design work.', price: 3200, originalPrice: 7500, category: 'Electronics', condition: 'Like New', location: 'Hostel Block D', image: '/airo-assets/images/listings/laptop', tag: 'Popular', tagColor: 'bg-violet-500' },
    { sellerId: 4, title: 'Kindle Paperwhite 10th Gen — 8GB', description: 'Kindle Paperwhite 10th gen, 8GB, waterproof. Used for 1.5 years. Screen perfect, battery lasts weeks. Comes with cover.', price: 5500, originalPrice: 12000, category: 'Electronics', condition: 'Good', location: 'Off Campus', image: '/airo-assets/images/listings/laptop', tag: null, tagColor: null },
    { sellerId: 5, title: 'Arduino Uno R3 Starter Kit', description: 'Arduino Uno R3 with full starter kit — breadboard, jumper wires, sensors, LEDs. Perfect for electronics projects and lab work.', price: 1200, originalPrice: 2800, category: 'Electronics', condition: 'Good', location: 'Hostel Block B', image: '/airo-assets/images/listings/laptop', tag: null, tagColor: null },
    { sellerId: 6, title: 'Raspberry Pi 4 Model B — 4GB RAM', description: 'Raspberry Pi 4 Model B, 4GB RAM. Comes with 32GB SD card, power supply, and case. Great for IoT and ML projects.', price: 4800, originalPrice: 8500, category: 'Electronics', condition: 'Like New', location: 'Hostel Block E', image: '/airo-assets/images/listings/laptop', tag: 'Verified', tagColor: 'bg-primary' },
    { sellerId: 7, title: 'Sony WF-1000XM4 True Wireless Earbuds', description: 'Sony WF-1000XM4 earbuds. Industry-leading ANC, 8 hours battery + 16 hours case. Used 4 months, excellent condition.', price: 9500, originalPrice: 20000, category: 'Electronics', condition: 'Like New', location: 'Girls Hostel A', image: '/airo-assets/images/listings/headphones', tag: 'Popular', tagColor: 'bg-violet-500' },
    { sellerId: 8, title: 'HP LaserJet Pro M15w Printer', description: 'HP LaserJet Pro wireless printer. Compact, prints 19 pages/min. Used for 2 years, works perfectly. Comes with extra toner.', price: 5500, originalPrice: 12000, category: 'Electronics', condition: 'Good', location: 'Hostel Block C', image: '/airo-assets/images/listings/laptop', tag: null, tagColor: null },
    { sellerId: 9, title: 'Wacom Intuos Small Drawing Tablet', description: 'Wacom Intuos Small CTL-4100 drawing tablet. Perfect for digital art, UI design, and note-taking. Used 6 months.', price: 2800, originalPrice: 6000, category: 'Electronics', condition: 'Good', location: 'Girls Hostel B', image: '/airo-assets/images/listings/laptop', tag: null, tagColor: null },
    { sellerId: 10, title: 'Anker 65W GaN USB-C Charger', description: 'Anker Nano II 65W GaN charger. Charges laptop, phone, and tablet simultaneously. Compact travel size. Like new condition.', price: 1800, originalPrice: 3500, category: 'Electronics', condition: 'Like New', location: 'Off Campus', image: '/airo-assets/images/listings/laptop', tag: null, tagColor: null },
    { sellerId: 1, title: 'Samsung 27" FHD Monitor — 75Hz', description: 'Samsung 27-inch FHD IPS monitor, 75Hz refresh rate. Perfect for coding and gaming. Minor stand scratch, panel perfect.', price: 8500, originalPrice: 16000, category: 'Electronics', condition: 'Good', location: 'Hostel Block A', image: '/airo-assets/images/listings/laptop', tag: null, tagColor: null },
    { sellerId: 2, title: 'Mechanical Keyboard — Keychron K2 (Brown Switch)', description: 'Keychron K2 TKL mechanical keyboard, brown switches. Wireless + wired. RGB backlight. Used 8 months, excellent condition.', price: 4200, originalPrice: 8500, category: 'Electronics', condition: 'Good', location: 'Girls Hostel C', image: '/airo-assets/images/listings/laptop', tag: 'Popular', tagColor: 'bg-violet-500' },
    { sellerId: 3, title: 'GoPro Hero 9 Black Action Camera', description: 'GoPro Hero 9 Black. 5K video, HyperSmooth 3.0 stabilization. Used for 1 year. Comes with 2 batteries, case, and mounts.', price: 18000, originalPrice: 38000, category: 'Electronics', condition: 'Good', location: 'Hostel Block D', image: '/airo-assets/images/listings/laptop', tag: null, tagColor: null },
    { sellerId: 4, title: 'TP-Link WiFi 6 Router — AX1800', description: 'TP-Link Archer AX21 WiFi 6 router. Dual band, covers 1500 sq ft. Perfect for hostel room. Used 6 months.', price: 2500, originalPrice: 5500, category: 'Electronics', condition: 'Good', location: 'Off Campus', image: '/airo-assets/images/listings/laptop', tag: null, tagColor: null },

    // ── BIKES (10) ──────────────────────────────────────────────────────────
    { sellerId: 3, title: 'Hero Sprint 26T Campus Bicycle', description: 'Great condition campus bicycle. Used for 1 year, recently serviced. New brake pads and tyres. Perfect for getting around campus quickly.', price: 3200, originalPrice: 6500, category: 'Bikes', condition: 'Good', location: 'Hostel Block D', image: '/airo-assets/images/listings/bicycle', tag: null, tagColor: null },
    { sellerId: 6, title: 'Atlas Cycle — 21 Speed Mountain Bike', description: 'Atlas 21-speed mountain bike. Shimano gears, front suspension. Used for 2 years, recently serviced. Great for campus and weekend rides.', price: 4500, originalPrice: 9000, category: 'Bikes', condition: 'Good', location: 'Hostel Block E', image: '/airo-assets/images/listings/bicycle', tag: null, tagColor: null },
    { sellerId: 8, title: 'BSA Ladybird 24T — Ladies Bicycle', description: 'BSA Ladybird 24-inch ladies bicycle. Light pink, good condition. Used for 1.5 years. New seat fitted recently.', price: 2800, originalPrice: 5500, category: 'Bikes', condition: 'Good', location: 'Hostel Block C', image: '/airo-assets/images/listings/bicycle', tag: null, tagColor: null },
    { sellerId: 10, title: 'Firefox Bikes Road Runner 700C', description: 'Firefox Road Runner 700C road bike. Lightweight alloy frame, 21 speeds. Used for 1 year. Perfect for long campus rides.', price: 6500, originalPrice: 14000, category: 'Bikes', condition: 'Good', location: 'Off Campus', image: '/airo-assets/images/listings/bicycle', tag: 'Popular', tagColor: 'bg-violet-500' },
    { sellerId: 1, title: 'Hercules Roadeo A50 MTB', description: 'Hercules Roadeo A50 mountain bike. 21-speed Shimano gears, dual disc brakes. Used for 6 months. Excellent condition.', price: 5800, originalPrice: 11000, category: 'Bikes', condition: 'Like New', location: 'Hostel Block A', image: '/airo-assets/images/listings/bicycle', tag: 'Like New', tagColor: 'bg-green-500' },
    { sellerId: 2, title: 'Decathlon Riverside 120 Hybrid Bike', description: 'Decathlon Riverside 120 hybrid bicycle. Comfortable for daily commute. Used for 8 months, well maintained.', price: 7200, originalPrice: 14500, category: 'Bikes', condition: 'Good', location: 'Girls Hostel C', image: '/airo-assets/images/listings/bicycle', tag: null, tagColor: null },
    { sellerId: 4, title: 'Hero Lectro C8i Electric Cycle', description: 'Hero Lectro C8i electric cycle. 25km range on single charge, pedal assist mode. Used for 1 year. Battery health 85%.', price: 18000, originalPrice: 35000, category: 'Bikes', condition: 'Good', location: 'Off Campus', image: '/airo-assets/images/listings/bicycle', tag: 'Hot Deal', tagColor: 'bg-red-500' },
    { sellerId: 5, title: 'Montra Trance 24 Kids/Teen Bike', description: 'Montra Trance 24-inch bike. Suitable for teens and short adults. 21 speeds, good condition. Selling as moving to bigger bike.', price: 3500, originalPrice: 7000, category: 'Bikes', condition: 'Good', location: 'Hostel Block B', image: '/airo-assets/images/listings/bicycle', tag: null, tagColor: null },
    { sellerId: 7, title: 'Btwin My Bike 7S Folding Bicycle', description: 'Btwin My Bike 7-speed folding bicycle. Folds compact for hostel storage. Used 6 months, excellent condition.', price: 9500, originalPrice: 19000, category: 'Bikes', condition: 'Like New', location: 'Girls Hostel A', image: '/airo-assets/images/listings/bicycle', tag: 'Verified', tagColor: 'bg-primary' },
    { sellerId: 9, title: 'Cycle Accessories Bundle — Lock, Lights, Pump', description: 'Complete cycle accessories: D-lock, front+rear LED lights, floor pump, and mudguards. All in good condition. Selling as a bundle.', price: 800, originalPrice: 2200, category: 'Bikes', condition: 'Good', location: 'Girls Hostel B', image: '/airo-assets/images/listings/bicycle', tag: 'Set Deal', tagColor: 'bg-amber-500' },

    // ── FURNITURE (10) ──────────────────────────────────────────────────────
    { sellerId: 4, title: 'Study Desk + Ergonomic Chair Set', description: 'Solid wood study desk (4ft x 2ft) with an ergonomic mesh chair. Both in excellent condition. Selling as a set only. Must pick up from hostel.', price: 4500, originalPrice: 9000, category: 'Furniture', condition: 'Like New', location: 'Off Campus', image: '/airo-assets/images/listings/desk-chair', tag: 'Set Deal', tagColor: 'bg-amber-500' },
    { sellerId: 6, title: 'IKEA KALLAX 4x4 Shelf Unit', description: 'IKEA KALLAX 4x4 shelf unit in white. 16 compartments, perfect for books and storage. Self-assembly required. Must pick up.', price: 3500, originalPrice: 7500, category: 'Furniture', condition: 'Good', location: 'Hostel Block E', image: '/airo-assets/images/listings/desk-chair', tag: null, tagColor: null },
    { sellerId: 8, title: 'Single Bed Frame with Storage', description: 'Wooden single bed frame with 2 storage drawers underneath. Fits standard single mattress. Disassembled for easy transport.', price: 5000, originalPrice: 11000, category: 'Furniture', condition: 'Good', location: 'Hostel Block C', image: '/airo-assets/images/listings/desk-chair', tag: null, tagColor: null },
    { sellerId: 10, title: 'Mini Fridge — 50L Haier', description: 'Haier 50L single-door mini fridge. Perfect for hostel room. Runs quietly, cools well. Used for 2 years, works perfectly.', price: 4200, originalPrice: 8500, category: 'Furniture', condition: 'Good', location: 'Off Campus', image: '/airo-assets/images/listings/desk-chair', tag: 'Popular', tagColor: 'bg-violet-500' },
    { sellerId: 1, title: 'Folding Study Table — Portable', description: 'Portable folding study table with adjustable height. Lightweight, easy to store. Perfect for bed studying. Used 6 months.', price: 800, originalPrice: 1800, category: 'Furniture', condition: 'Good', location: 'Hostel Block A', image: '/airo-assets/images/listings/desk-chair', tag: null, tagColor: null },
    { sellerId: 2, title: 'Bean Bag Chair — XL Size', description: 'XL bean bag chair in dark grey. Comfortable for reading and gaming. Used 1 year, filling still good. Easy to carry.', price: 1200, originalPrice: 3000, category: 'Furniture', condition: 'Good', location: 'Girls Hostel C', image: '/airo-assets/images/listings/desk-chair', tag: null, tagColor: null },
    { sellerId: 3, title: 'Bookshelf — 5 Tier Wooden', description: '5-tier wooden bookshelf, 180cm tall. Holds 100+ books. Solid construction, minor scratch on bottom shelf. Must pick up.', price: 2800, originalPrice: 6000, category: 'Furniture', condition: 'Good', location: 'Hostel Block D', image: '/airo-assets/images/listings/desk-chair', tag: null, tagColor: null },
    { sellerId: 5, title: 'Whiteboard — 3ft x 2ft Magnetic', description: 'Magnetic whiteboard 3ft x 2ft. Comes with 4 markers and eraser. Perfect for study room or hostel wall. Used 1 year.', price: 900, originalPrice: 2200, category: 'Furniture', condition: 'Good', location: 'Hostel Block B', image: '/airo-assets/images/listings/desk-chair', tag: null, tagColor: null },
    { sellerId: 7, title: 'Clothes Rack — Freestanding Steel', description: 'Freestanding steel clothes rack with 2 tiers. 120cm wide, holds 20+ hangers. Used 8 months, sturdy and rust-free.', price: 600, originalPrice: 1500, category: 'Furniture', condition: 'Good', location: 'Girls Hostel A', image: '/airo-assets/images/listings/desk-chair', tag: null, tagColor: null },
    { sellerId: 9, title: 'Floor Lamp — LED Dimmable', description: 'LED floor lamp with 3 brightness levels and warm/cool light modes. USB charging port on base. Perfect for study corner.', price: 1400, originalPrice: 3200, category: 'Furniture', condition: 'Like New', location: 'Girls Hostel B', image: '/airo-assets/images/listings/desk-chair', tag: null, tagColor: null },

    // ── CLOTHING (15) ───────────────────────────────────────────────────────
    { sellerId: 1, title: 'IIT Bombay Hoodie — Size L', description: 'Official college hoodie, worn only twice. Washed and in perfect condition. Size L, fits true to size. Great for cold hostel nights.', price: 650, originalPrice: 1400, category: 'Clothing', condition: 'Like New', location: 'Hostel Block A', image: '/airo-assets/images/listings/jacket', tag: null, tagColor: null },
    { sellerId: 2, title: 'North Face Thermoball Jacket — Size M', description: 'North Face Thermoball Eco jacket in black, size M. Lightweight and warm. Used for 1 winter season. No damage or stains.', price: 4500, originalPrice: 12000, category: 'Clothing', condition: 'Like New', location: 'Girls Hostel C', image: '/airo-assets/images/listings/jacket', tag: 'Popular', tagColor: 'bg-violet-500' },
    { sellerId: 3, title: 'Levi\'s 511 Slim Fit Jeans — 32x32', description: 'Levi\'s 511 slim fit jeans in dark indigo. Size 32x32. Worn a few times, excellent condition. No fading or damage.', price: 1200, originalPrice: 3500, category: 'Clothing', condition: 'Like New', location: 'Hostel Block D', image: '/airo-assets/images/listings/jacket', tag: null, tagColor: null },
    { sellerId: 4, title: 'Nike Dri-FIT Running T-Shirts — Pack of 3', description: 'Pack of 3 Nike Dri-FIT running t-shirts in blue, grey, and black. Size L. Worn a few times each, washed and clean.', price: 900, originalPrice: 2700, category: 'Clothing', condition: 'Good', location: 'Off Campus', image: '/airo-assets/images/listings/jacket', tag: 'Set Deal', tagColor: 'bg-amber-500' },
    { sellerId: 5, title: 'Adidas Ultraboost 21 Running Shoes — Size 9', description: 'Adidas Ultraboost 21 in white/grey. Size 9 (UK). Used for 6 months, soles still good. Cleaned and ready.', price: 4800, originalPrice: 13000, category: 'Clothing', condition: 'Good', location: 'Hostel Block B', image: '/airo-assets/images/listings/jacket', tag: null, tagColor: null },
    { sellerId: 6, title: 'Formal Shirt + Trouser Set — Interview Ready', description: 'Light blue formal shirt (size 40) + black formal trousers (size 32). Worn for 2 interviews. Dry cleaned and pressed.', price: 700, originalPrice: 2200, category: 'Clothing', condition: 'Good', location: 'Hostel Block E', image: '/airo-assets/images/listings/jacket', tag: 'Set Deal', tagColor: 'bg-amber-500' },
    { sellerId: 7, title: 'Zara Oversized Blazer — Size S/M', description: 'Zara oversized blazer in camel/beige. Size S/M. Worn twice for college events. Perfect for presentations and placements.', price: 1800, originalPrice: 5500, category: 'Clothing', condition: 'Like New', location: 'Girls Hostel A', image: '/airo-assets/images/listings/jacket', tag: 'Verified', tagColor: 'bg-primary' },
    { sellerId: 8, title: 'Puma Sports Shorts — Pack of 2', description: 'Pack of 2 Puma sports shorts in black and navy. Size M. Perfect for gym and sports. Used a few times, washed clean.', price: 500, originalPrice: 1400, category: 'Clothing', condition: 'Good', location: 'Hostel Block C', image: '/airo-assets/images/listings/jacket', tag: null, tagColor: null },
    { sellerId: 9, title: 'H&M Winter Sweater — Size M', description: 'H&M chunky knit sweater in olive green. Size M. Worn 3-4 times. No pilling or damage. Great for campus winters.', price: 600, originalPrice: 1800, category: 'Clothing', condition: 'Good', location: 'Girls Hostel B', image: '/airo-assets/images/listings/jacket', tag: null, tagColor: null },
    { sellerId: 10, title: 'Woodland Trekking Boots — Size 8', description: 'Woodland waterproof trekking boots in brown. Size 8 (UK). Used for 2 treks. Soles in good condition, upper leather intact.', price: 2200, originalPrice: 5500, category: 'Clothing', condition: 'Good', location: 'Off Campus', image: '/airo-assets/images/listings/jacket', tag: null, tagColor: null },
    { sellerId: 1, title: 'College Tracksuit — Size L (Blue)', description: 'Official college tracksuit in royal blue. Size L. Used for sports day and gym. Washed and in good condition.', price: 450, originalPrice: 1200, category: 'Clothing', condition: 'Good', location: 'Hostel Block A', image: '/airo-assets/images/listings/jacket', tag: null, tagColor: null },
    { sellerId: 2, title: 'Saree — Silk Cotton (Festive)', description: 'Beautiful silk cotton saree in maroon with gold border. Worn once for college cultural fest. Comes with matching blouse piece.', price: 1500, originalPrice: 4500, category: 'Clothing', condition: 'Like New', location: 'Girls Hostel C', image: '/airo-assets/images/listings/jacket', tag: null, tagColor: null },
    { sellerId: 3, title: 'Rain Jacket — Decathlon Forclaz', description: 'Decathlon Forclaz 300 rain jacket in yellow. Size M. Waterproof, taped seams. Used for 2 treks. Excellent condition.', price: 1200, originalPrice: 3000, category: 'Clothing', condition: 'Good', location: 'Hostel Block D', image: '/airo-assets/images/listings/jacket', tag: null, tagColor: null },
    { sellerId: 4, title: 'Backpack — Wildcraft 45L Trekking', description: 'Wildcraft 45L trekking backpack in grey. Multiple compartments, rain cover included. Used for 3 treks. Good condition.', price: 1800, originalPrice: 4500, category: 'Clothing', condition: 'Good', location: 'Off Campus', image: '/airo-assets/images/listings/jacket', tag: null, tagColor: null },
    { sellerId: 5, title: 'Sunglasses — Ray-Ban Wayfarer (Unisex)', description: 'Ray-Ban Wayfarer RB2140 in classic black. Unisex. Comes with original case and cleaning cloth. Minor frame wear.', price: 2500, originalPrice: 7000, category: 'Clothing', condition: 'Good', location: 'Hostel Block B', image: '/airo-assets/images/listings/jacket', tag: null, tagColor: null },

    // ── MUSIC (10) ──────────────────────────────────────────────────────────
    { sellerId: 6, title: 'Yamaha F310 Acoustic Guitar', description: 'Yamaha F310 acoustic guitar. Full size, spruce top. Used for 1.5 years. Comes with bag, capo, picks, and extra strings.', price: 4500, originalPrice: 9000, category: 'Music', condition: 'Good', location: 'Hostel Block E', image: '/airo-assets/images/listings/headphones', tag: 'Popular', tagColor: 'bg-violet-500' },
    { sellerId: 7, title: 'Casio CT-S300 Keyboard — 61 Keys', description: 'Casio CT-S300 portable keyboard, 61 keys. 48 polyphony, 100 tones. Comes with adapter and stand. Used 8 months.', price: 2800, originalPrice: 5500, category: 'Music', condition: 'Good', location: 'Girls Hostel A', image: '/airo-assets/images/listings/headphones', tag: null, tagColor: null },
    { sellerId: 8, title: 'Cajon Box Drum — Meinl', description: 'Meinl cajon box drum in natural wood finish. Snare wires inside for crisp sound. Used for college band practice. Good condition.', price: 3200, originalPrice: 7000, category: 'Music', condition: 'Good', location: 'Hostel Block C', image: '/airo-assets/images/listings/headphones', tag: null, tagColor: null },
    { sellerId: 9, title: 'Ukulele — Soprano Size (Mahogany)', description: 'Soprano ukulele in mahogany finish. Comes with bag, tuner, and chord chart. Perfect for beginners. Used 6 months.', price: 1200, originalPrice: 2800, category: 'Music', condition: 'Good', location: 'Girls Hostel B', image: '/airo-assets/images/listings/headphones', tag: null, tagColor: null },
    { sellerId: 10, title: 'Audio-Technica ATH-M20x Studio Headphones', description: 'Audio-Technica ATH-M20x professional studio headphones. Flat response, great for music production. Used 1 year.', price: 2200, originalPrice: 4500, category: 'Music', condition: 'Good', location: 'Off Campus', image: '/airo-assets/images/listings/headphones', tag: null, tagColor: null },
    { sellerId: 1, title: 'Focusrite Scarlett Solo USB Audio Interface', description: 'Focusrite Scarlett Solo 3rd gen audio interface. 1 mic + 1 instrument input. Perfect for home recording. Used 1 year.', price: 5500, originalPrice: 11000, category: 'Music', condition: 'Like New', location: 'Hostel Block A', image: '/airo-assets/images/listings/headphones', tag: 'Verified', tagColor: 'bg-primary' },
    { sellerId: 2, title: 'Tabla Set — Beginner Grade', description: 'Beginner-grade tabla set (dayan + bayan). Good sound, heads in good condition. Comes with carry bag and tuning hammer.', price: 2500, originalPrice: 5500, category: 'Music', condition: 'Good', location: 'Girls Hostel C', image: '/airo-assets/images/listings/headphones', tag: null, tagColor: null },
    { sellerId: 3, title: 'Violin — 4/4 Full Size with Bow & Case', description: 'Full-size 4/4 violin with bow and hard case. Used for 2 years of lessons. Good tone, recently restrung.', price: 3500, originalPrice: 8000, category: 'Music', condition: 'Good', location: 'Hostel Block D', image: '/airo-assets/images/listings/headphones', tag: null, tagColor: null },
    { sellerId: 4, title: 'Bose SoundLink Mini II Bluetooth Speaker', description: 'Bose SoundLink Mini II. 360-degree sound, 10 hours battery. Used 1 year. Minor scratch on base, sound perfect.', price: 6500, originalPrice: 14000, category: 'Music', condition: 'Good', location: 'Off Campus', image: '/airo-assets/images/listings/headphones', tag: null, tagColor: null },
    { sellerId: 5, title: 'Harmonium — Paloma 9 Scale', description: 'Paloma 9-scale harmonium. 3.5 octaves, double bellows. Used for college music club. Good condition, all keys working.', price: 4000, originalPrice: 9000, category: 'Music', condition: 'Good', location: 'Hostel Block B', image: '/airo-assets/images/listings/headphones', tag: null, tagColor: null },

    // ── NOTES (10) ──────────────────────────────────────────────────────────
    { sellerId: 6, title: 'GATE CS 2024 Handwritten Notes — Complete', description: 'Complete GATE CS handwritten notes covering all 10 subjects. Topicwise, with solved PYQs. Prepared by GATE AIR 45 student.', price: 800, originalPrice: 2000, category: 'Notes', condition: 'Like New', location: 'Hostel Block E', image: '/airo-assets/images/listings/textbooks', tag: 'Hot Deal', tagColor: 'bg-red-500' },
    { sellerId: 7, title: 'Data Structures & Algorithms Notes — Semester 3', description: 'Detailed DSA notes with diagrams, complexity analysis, and code snippets. Covers arrays, trees, graphs, DP. Scored 9.2 CGPA.', price: 200, originalPrice: 500, category: 'Notes', condition: 'Good', location: 'Girls Hostel A', image: '/airo-assets/images/listings/textbooks', tag: null, tagColor: null },
    { sellerId: 8, title: 'Machine Learning Notes — Andrew Ng Course', description: 'Handwritten notes from Andrew Ng ML course + college ML subject. Covers regression, SVM, neural networks, clustering.', price: 350, originalPrice: 800, category: 'Notes', condition: 'Good', location: 'Hostel Block C', image: '/airo-assets/images/listings/textbooks', tag: 'Popular', tagColor: 'bg-violet-500' },
    { sellerId: 9, title: 'Chemistry Lab Manual — Sem 1 & 2', description: 'Complete chemistry lab manual with all experiments, observations, and results filled. Useful as reference for upcoming batches.', price: 150, originalPrice: 400, category: 'Notes', condition: 'Good', location: 'Girls Hostel B', image: '/airo-assets/images/listings/textbooks', tag: null, tagColor: null },
    { sellerId: 10, title: 'Placement Prep Notes — DSA + System Design', description: 'Comprehensive placement prep notes covering 150+ DSA problems with solutions and system design concepts. Helped crack Google.', price: 500, originalPrice: 1200, category: 'Notes', condition: 'Like New', location: 'Off Campus', image: '/airo-assets/images/listings/textbooks', tag: 'Verified', tagColor: 'bg-primary' },
    { sellerId: 1, title: 'Engineering Physics Notes — Sem 1', description: 'First semester Engineering Physics notes. Covers quantum mechanics, optics, lasers, and fiber optics. Clear diagrams.', price: 120, originalPrice: 300, category: 'Notes', condition: 'Good', location: 'Hostel Block A', image: '/airo-assets/images/listings/textbooks', tag: null, tagColor: null },
    { sellerId: 2, title: 'DBMS Complete Notes with SQL Queries', description: 'Complete DBMS notes with ER diagrams, normalization, transaction management, and 50+ SQL query examples.', price: 180, originalPrice: 450, category: 'Notes', condition: 'Good', location: 'Girls Hostel C', image: '/airo-assets/images/listings/textbooks', tag: null, tagColor: null },
    { sellerId: 3, title: 'CAT Quant Preparation Notes', description: 'CAT quantitative aptitude notes covering arithmetic, algebra, geometry, and number theory. 200+ solved problems.', price: 400, originalPrice: 1000, category: 'Notes', condition: 'Good', location: 'Hostel Block D', image: '/airo-assets/images/listings/textbooks', tag: null, tagColor: null },
    { sellerId: 4, title: 'Computer Networks Notes — OSI & TCP/IP', description: 'Detailed computer networks notes with protocol diagrams, subnetting examples, and routing algorithms. Exam-ready format.', price: 160, originalPrice: 400, category: 'Notes', condition: 'Good', location: 'Off Campus', image: '/airo-assets/images/listings/textbooks', tag: null, tagColor: null },
    { sellerId: 5, title: 'Analog Electronics Notes — BJT, MOSFET, Op-Amp', description: 'Analog electronics notes covering BJT, MOSFET, op-amp circuits with solved numericals. Used to score 92/100.', price: 220, originalPrice: 550, category: 'Notes', condition: 'Good', location: 'Hostel Block B', image: '/airo-assets/images/listings/textbooks', tag: null, tagColor: null },

    // ── SPORTS (5) ──────────────────────────────────────────────────────────
    { sellerId: 6, title: 'Yonex Badminton Racket — Arcsaber 11', description: 'Yonex Arcsaber 11 badminton racket. 4U weight, G5 grip. Used for 1 year. Restrung 3 months ago. Comes with cover.', price: 2800, originalPrice: 6500, category: 'Sports', condition: 'Good', location: 'Hostel Block E', image: '/airo-assets/images/listings/bicycle', tag: null, tagColor: null },
    { sellerId: 7, title: 'Cricket Kit — Complete Set', description: 'Complete cricket kit: bat (SG), pads, gloves, helmet, thigh guard, and kit bag. Used for 1 season. Good condition.', price: 3500, originalPrice: 8000, category: 'Sports', condition: 'Good', location: 'Girls Hostel A', image: '/airo-assets/images/listings/bicycle', tag: 'Set Deal', tagColor: 'bg-amber-500' },
    { sellerId: 8, title: 'Decathlon Yoga Mat — 8mm Thick', description: 'Decathlon Domyos 8mm yoga mat in purple. Non-slip, easy to clean. Used for 6 months. Comes with carry strap.', price: 600, originalPrice: 1500, category: 'Sports', condition: 'Good', location: 'Hostel Block C', image: '/airo-assets/images/listings/bicycle', tag: null, tagColor: null },
    { sellerId: 9, title: 'Adjustable Dumbbell Set — 2kg to 10kg', description: 'Adjustable dumbbell set with 5 weight levels per dumbbell (2-10kg). Perfect for hostel room workouts. Good condition.', price: 2200, originalPrice: 5000, category: 'Sports', condition: 'Good', location: 'Girls Hostel B', image: '/airo-assets/images/listings/bicycle', tag: 'Popular', tagColor: 'bg-violet-500' },
    { sellerId: 10, title: 'Nivia Football — Size 5', description: 'Nivia Storm size 5 football. Used for college intramurals. Good condition, holds air well. Ready to play.', price: 400, originalPrice: 900, category: 'Sports', condition: 'Good', location: 'Off Campus', image: '/airo-assets/images/listings/bicycle', tag: null, tagColor: null },
  ]);

  // ── Seed reviews ──────────────────────────────────────────────────────────
  await db.insert(reviews).values([
    { listingId: 1,  userId: 2,  rating: 5, text: 'Great seller! Books exactly as described. Quick handover near the library.' },
    { listingId: 1,  userId: 3,  rating: 4, text: 'Good condition, fair price. Recommended!' },
    { listingId: 21, userId: 1,  rating: 5, text: 'MacBook is perfect. Priya was very honest about the condition. Smooth transaction.' },
    { listingId: 23, userId: 4,  rating: 4, text: 'Dell laptop works great. Minor scratches as mentioned. Good deal.' },
    { listingId: 22, userId: 1,  rating: 5, text: 'Headphones are amazing. Dev packed them carefully. Very happy!' },
    { listingId: 22, userId: 3,  rating: 5, text: 'Exactly as described. Fast response from seller.' },
    { listingId: 41, userId: 2,  rating: 4, text: 'Bicycle in good shape. Rohan was punctual for the meetup.' },
    { listingId: 51, userId: 5,  rating: 5, text: 'Desk and chair are solid. Helped a lot with late-night study sessions.' },
    { listingId: 61, userId: 6,  rating: 5, text: 'Hoodie is exactly as described. Super warm and cozy!' },
    { listingId: 71, userId: 7,  rating: 4, text: 'Guitar sounds great for the price. Bag and accessories are a bonus.' },
    { listingId: 81, userId: 8,  rating: 5, text: 'GATE notes are incredibly detailed. Worth every rupee!' },
    { listingId: 91, userId: 9,  rating: 4, text: 'Badminton racket in good shape. Seller was responsive and helpful.' },
    { listingId: 3,  userId: 10, rating: 5, text: 'CLRS is a gem. Condition is exactly as described. Happy with the purchase.' },
    { listingId: 7,  userId: 2,  rating: 5, text: 'Discrete Maths notes are super clean. Ananya is a great seller!' },
    { listingId: 29, userId: 3,  rating: 4, text: 'Casio calculator works perfectly. Great deal for the price.' },
  ]);

  console.log('✅ Seeding complete! 100 listings added.');
}

seed().catch(console.error).finally(() => process.exit(0));
